mergeable:
  pull_requests:
    stale:
      days: 14
      message: 'This PR is stale. Please follow up!'

    label:
      must_include:
        regex: '(feature)|(bug)|(docs)|(enhancement)|(miscellaneous)|(release)|(tests)|(ci)|(poc)|(dont merge)|(dependencies)|(miscellaneous)'
        message: 'Can you please add a valid label! [One of (feature) / (docs) / (bug) / (enhancement) / (miscellaneous) / (release) / (tests) / (ci) / (poc) / (dont merge) / (dependencies) / (miscellaneous)]'
      must_exclude:
        regex: '(do-not-merge)'
        message: 'This PR is work in progress. Cannot be merged yet.'

    description:
      no_empty:
        enabled: true
        message: 'Can you please add a description!'
      must_exclude:
        regex: 'do not merge'
        message: 'This PR is work in progress. Cannot be merged yet.'
