# Tells Travis we're running on a Node environment
language: node_js
node_js: "8"
cache: yarn

install:
  - yarn install

jobs:
  include:
    ##############################  TEST STAGE ##############################
    # Runs on all (PRs/Branches)
    # Runs the unit tests and the coverage reports
    # Also uploads the coverage reports to codecov
    # @TODO: Generate a storybook preview link
    - stage: test
    - script:
        - yarn test
        - yarn coverage
      name: "Run Tests & Coverage"
    #########################################################################

    #########################  PRE RELEASE (MASTER) #########################
    # This only runs on the develop branch
    #
    # Phase - 1 : DOCUMENTATION
    # Generate the documentation [storybook] on /next
    # Upload the documentation to the gh-pages branch
    #
    # Phase - 2 : NPM relements@NEXT RELEASE
    # Trigger the npm build script
    # Trigger the semantic-release script which bumps package versions according to commits
    # Publish the new release to npm under the @next dist-tag
    #
    - stage: develop
    - script:
        - yarn build
        - yarn semantic-release
      name: "Build & Deploy Relements"
    - script: yarn build:storybook:next
      name: "Deploy documentation"
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local_dir: storybook-static
        repo: hellohaptik/relements
        target_branch: gh-pages
        on:
          branch: develop
    - script: yarn build
      name: "Deploy to npm"
      deploy:
        provider: npm
        email: "pratham.agrawal92@gmail.com"
        api_key: $NPM_TOKEN
        on:
          branch: develop
          tag: next
    #########################################################################

    ###################  PUBLISH RELEASE (RELEASE BRANCH) ###################
    # This only runs on the release branch
    #
    # Phase - 1 : DOCUMENTATION
    # Generate the documentation [storybook] on the root point
    # Upload the documentation to the gh-pages branch
    #
    # Phase - 2 : NPM relements RELEASE
    # Trigger the npm build script
    # Trigger the semantic-release script which
    #   - Bumps package versions according to commits
    #   - Generates Release Notes
    #   - Generates Git Tag
    #   - Publishes release to github
    # Publish the new release to npm under the @next dist-tag
    #
    - stage: release
    - script:
        - yarn build
        - yarn semantic-release
      name: "Build & Deploy Relements"
    - script: yarn build:storybook
      name: "Deploy documentation"
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local_dir: storybook-static
        repo: hellohaptik/relements
        target_branch: gh-pages
        on:
          branch: release
    - script: yarn build
      name: "Deploy to npm"
      deploy:
        provider: npm
        email: "pratham.agrawal92@gmail.com"
        api_key: $NPM_TOKEN
        on:
          branch: release

stages:
  - test
  - name: develop
    if: branch = develop
  - name: release
    if: branch = release
